--CHAR/VARCHAR/NVARCHAR

DECLARE @MyChar CHAR(10)='Test'
DECLARE @MyVarChar VARCHAR(10)='Test'
DECLARE @MyNVarChar NVARCHAR(10)='Test'

SELECT DATALENGTH (@MyChar) AS MyChar, DATALENGTH ( @MyVarChar) AS MyVarChar, DATALENGTH (@MyNVarChar) AS MyNVarChar